"""empty message

Revision ID: 794a7e4b282e
Revises: 118016a906e3
Create Date: 2017-12-20 17:11:59.251719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794a7e4b282e'
down_revision = '118016a906e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_room')
    # ### end Alembic commands ###
