"""empty message

Revision ID: f6d96b7327fb
Revises: 58017f865d29
Create Date: 2017-12-22 07:36:19.833326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d96b7327fb'
down_revision = '58017f865d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_author_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_author_id_fkey', 'messages', 'users', ['author_id'], ['id'])
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
